OptimalScale/LMFlow

examples/evaluate.py, src/lmflow/args.py, src/lmflow/models/hf_decoder_model.py, src/lmflow/pipeline/evaluator.py
- add ppl evaluation as one metric of evaluate function of Evaluator.
- some statistic for reference(wikitext-2-raw-v1 data and RTX 3090) : ppl for gpt2, gpt2-large, got-neo2.7B, original LLaMA and LLaMA + LoRA-380k are 25.3, 16.4, 13, 5.3, 5.6 respectively .
- fix a bug which will lead to copy meta tensor, no data error : ram optimised offload seems currently not supported by LLaMA (no matter LoRA), so we currently automatically convert to original loading without offloading for LLaMA.
=> Support ppl as one of the evaluation metrics and fix bug for llama offload loading

src/lmflow/args.py, src/lmflow/pipeline/evaluator.py
- check datatype before do ppl evaluation
- set the default evaluation metric to accuracy, as it is the most common metric used
=> Bug Fix: restrict dataset type for ppl evaluation

src/lmflow/pipeline/raft_aligner.py
Caused by RAFT trainer initialization. Single GPU doesn't support empty training dataset.
=> Fix single GPU error for raft

src/lmflow/args.py, src/lmflow/models/hf_decoder_model.py
Support diy lora_target_modules layer.
For example, for LLaMA, you can use `--lora_target_modules q_proj k_proj v_proj o_proj` for more layers.
=> LoRA-layer-support

configs/ds_config_eval.json, src/lmflow/datasets/__init__.py, src/lmflow/models/hf_decoder_model.py, src/lmflow/pipeline/evaluator.py
Fix text2text nll
- Take sequence length into account
- Sequence length -= 1 if first token is not -100 (since in transformers the first token is ignored, e.g. [gpt2](https://github.com/huggingface/transformers/blob/15641892985b1d77acc74c9065c332cd7c3f7d7f/src/transformers/models/gpt2/modeling_gpt2.py#L1105).
- Fix dataset import problem in `src/lmflow/datasets/__init__.py`
- Fix unfair comparison between models caused by `add_special_tokens`
- Add input/output/full nll printing for "text2text" typed dataset
Currently this metric can only be used to roughly compare model quality. If model quality has huge difference, this metric can reflect the quality gap. Otherwise, the comparison may be meaningless. Some metrics are shown as a reference (in our hold-out dataset which contains 50 …
=> Fix text2text nll

requirements.txt, scripts/run_finetune_with_lora_save_aggregated_weights.sh
- Add missing dependency
- Use `data/alpha/test` as the evaluation set for `run_finetune_with_lora_save_aggregated_weights.sh`, so it is available to our users.
- Fix typo: evaluation_strategy -> eval_strategy
=> Fix bugs of runtime evaluation

configs/accelerator_multiGPU_config.yaml, configs/accelerator_singleGPU_config.yaml, examples/evaluate.py, scripts/run_evaluation_accelerator.sh, src/lmflow/args.py, src/lmflow/models/hf_decoder_model.py, src/lmflow/models/hf_encoder_decoder_model.py, src/lmflow/pipeline/evaluator.py
- User can choose either Deepspeed or Accelerator now (Default still to Deepspeed) with argument.
- With Accelerator, all models can be ram_optimized load (w/o lora) which significantly save cpu memory. Under my testing, with singleGPU, it can save 2x memory and extend to 2~5x in multiGPU setting.
- Unittests passed and accuracy experiments conducted under various multiGPU and multi batch setting which obtained similar results to previous.
- Accelerator config and example scripts provided
=> Support Accelerator for Evaluator

src/lmflow/datasets/dataset.py, src/lmflow/models/hf_decoder_model.py
When dill fails to serialize the tokenization transformation, huggingface uses pseudo-random fingerprint to reuse the dataset cache, this results in a serious bug: models with different tokenizers + same dataset generate and reuse the same data cache. We now handle the fingerprint generation by ourselves with
new_fingerprint = md5(dataset.fingerprint + str(tokenizer))
=> Fix hf fingerprint cache issue of tokenization

docs/source/examples/raft.md, src/lmflow/pipeline/raft_aligner.py
If all the samples in a local batch are ``bad'', we do not take them into the SFT dataset. So we should be more careful about the index of the list to avoid out-of-range error.
=> fix the index bug

scripts/data_preprocess/concat_shuffle_split.py, scripts/data_preprocess/run_data_preprocess.sh
This script is designed for handling large datasets. 
It merges multiple datasets located in the same directory, shuffles them, and splits them into training, evaluation, and testing sets. 
The training set is further divided into k folds.
Finally, three new folders (/eval, /test, /trainkfolds) will be generated under the --output_path.
=> add large data preprocess script

src/lmflow/pipeline/inferencer.py
using `max_new_tokens=self.inferencer_args.max_new_tokens` will make stream_inference useless
=> fix_inferency.py

README.md, configs/ds_config_zero2.json, requirements.txt
1.   can't use `CUDA_VISIBLE_DEVICES` with new DeepSpeed, need to use `deepspeed  --include localhost:0,1`
https://github.com/microsoft/DeepSpeed/issues/662
2.   hf scheduler + ds optimizer no longer supported, need to rewrite deepspeed config
https://github.com/huggingface/transformers/issues/24359#issuecomment-1600085236
=> Dev update transformers

requirements.txt, scripts/run_finetune_with_qlora_save_aggregated_weights.sh, setup.py, src/lmflow/args.py, src/lmflow/models/hf_decoder_model.py
I have added arguments under model_args to enable QLoRA support. Namely arguments are:
-  use_qlora: bool (default: False)
-  bits: int = (default 4, wtih choices between 4,8)
-  quant_type: str = 'nf4' default with optional choice of 'fp4'
-  double_quant: bool = (default: True)
Is model_args.use_qlora is set to 1/True, it also sets model_arga.lora to True so the entire pipeline works.
=> Added QLoRA support for Decoder transformers with tune_strategy "Normal"

src/lmflow/models/hf_decoder_model.py
- Now data types "text2text" and future data types are also supported
- Fix the bug when model_max_length is not provided (such as +inf)
=> Support all types with `--disable_group_texts 1`

src/lmflow/utils/flash_attention/llama_flash_attention.py
fix bugs in llama2-70b multi-query attention
=> fix bugs in llama flash attention

requirements.txt
Hello!
In transformers 4.35.0, the developers deleted names `is_fairscale_available` and `default_hp_search_backend` from `transformers.integrations`, which causes errors since LMFlow actively tries to find the names in those locations.
As a quick workaround, I propose to change the requirements.txt and add a condition `transformers<4.35.0`.
=> fix bugs in requirements.txt since previous one can cause errors

examples/detail_memory.py, scripts/run_detail_gpu_memory.sh
To start checking the GPU memory usage at each step during a normal training process, execute the following command: bash  `./scripts/run_detail_gpu_memory.sh`.  
The script runs without gradient checkpointing, DeepSpeed, or Flash Attention, and only includes the base training process.
=> add GPU memory check script

configs/accelerator_multigpu_config.yaml, configs/ds_config_zero3.json, examples/chatbot.py, requirements.txt, scripts/run_chatbot.sh, src/lmflow/args.py, src/lmflow/models/hf_decoder_model.py, src/lmflow/pipeline/inferencer.py, src/lmflow/utils/flash_attention/llama_flash_attention.py
Use accelerate to support multi-gpu chatbot
=> Support multi-gpu inference

readme/flash_attn2.md, src/lmflow/models/hf_decoder_model.py
When importing "flash_attn", there's a possibility of encountering errors other than "ModuleNotFound". 
These errors will also be ignored by the try/except clause, potentially leading users to mistakenly believe that they have successfully imported flash_attn.
=> add more info when fail to import flash attn

install.sh, requirements.txt, scripts/run_finetune_with_lisa.sh, src/lmflow/models/hf_decoder_model.py
- Also, export `--batch_size` for `scripts/run_finetune_with_lisa.sh`
=> Add latest support for flash-attention from hf

requirements.txt
- The mistral issue in transformers==4.38.x no longer appears in latest 4.39.2
=> Update dependency for `transformers`

src/lmflow/args.py
- This is the more reasonable default for fine-tuning. False value is more commonly used in pretrain.
=> Change `--disable_group_texts` default to True

README.md, readme/README_zh-hans.md
Update readme for Chinese users.
=> readme (zh) update

src/lmflow/args.py, src/lmflow/datasets/dataset.py, src/lmflow/models/hf_decoder_model.py, src/lmflow/utils/constants.py, src/lmflow/utils/conversation_formatter.py, src/lmflow/utils/conversation_template.py, tests/models/test_hf_decoder_model.py, tests/utils/test_conversation_formatter.py, tests/utils/test_conversation_template.py
=> conversation dataset (sharegpt format) custom template dev

docs/source/examples/DATASETS.md
conversation template doc typo fix
=> conversation template doc typo fix

docs/source/examples/DATASETS.md, docs/source/examples/supported_conversation_template.md
=> template info update

docs/source/examples/DATASETS.md, docs/source/examples/customize_conversation_template.md, src/lmflow/utils/conversation_formatter.py
1. Custom conversation template improvement, when `content` is empty(""), send a warning info and add a space to it. 
2. Document update, switch the order of supported dataset format.
3. Customize conversation template document update.
=> Custom conversation template improvement and document update

readme/README_es.md, readme/README_hindi.md, readme/README_jp.md, readme/README_ko.md, readme/README_zh-hans.md
README update, remove lora save aggregate shell
We will bring this function back soon. Stay tuned!
=> README update, remove lora save aggregate shell

README.md, examples/merge_lora.py, scripts/run_finetune_with_lora.sh, scripts/run_merge_lora.sh, src/lmflow/models/hf_decoder_model.py
Users can now merge LoRA weight and the base model into one using:  
```sh
./scripts/run_merge_lora.sh \
--model_name_or_path Qwen/Qwen1.5-1.8B \
--lora_model_path output_models/lora \
--output_model_path output_models/lora_merged \
```
=> Merge LoRA and base model

readme/README_ko.md
=> README kr update

readme/README_jp.md
=> README jp update

docs/source/examples/supported_conversation_template.md, src/lmflow/utils/conversation_template/chatglm.py
Add chatglm3 template, tests need to be done.
=> Add chatglm3 template

docs/source/examples/customize_conversation_template.md, src/lmflow/utils/conversation_template/base.py
Customized conversation template update
=> Customized conversation template guide update

docs/source/examples/customize_conversation_template.md, docs/source/examples/reward_modeling.md
1. Customize conversation template guide update
2. Reward modeling guide update (partial)
=> Guide update

docs/source/examples/finetuning.md, docs/source/examples/index.md, docs/source/examples/reward_modeling.md
=> Add finetuning doc

contrib/rlhflow/reward_modeling.py, contrib/rlhflow/run_reward_modeling.sh, data/download.sh, examples/reward_modeling.py, scripts/run_reward_modeling.sh, scripts/run_reward_modeling_with_lisa.sh, scripts/run_reward_modeling_with_lora.sh, src/lmflow/args.py, src/lmflow/datasets/dataset.py, src/lmflow/models/auto_model.py, src/lmflow/models/hf_text_regression_model.py, src/lmflow/pipeline/auto_pipeline.py, src/lmflow/pipeline/rm_tuner.py, src/lmflow/pipeline/utils/rm_dataprocessor.py, src/lmflow/pipeline/utils/rm_trainer.py, src/lmflow/utils/constants.py, src/lmflow/utils/conversation_template/__init__.py
[Ready for review]
Reward modeling support
Tested on:
1. Full finetuning
2. LoRA
3. LISA
=> Reward modeling support

README.md, docs/source/examples/supported_conversation_template.md
Support Qwen2 models.
Only docs are updated, since the pipeline requirements are the same as Qwen1.5.
1. Full-Finetune
2 LoRA
> **Note: This isn't a bug in LMFlow, but we will add a logger notification ASAP to notify users when they might trigger this bug.** 
When do lora (or other peft tuning that uses `peft` library) first and saved model at a dir, say, A, and then do another finetuning work that also specifies the same `output_dir` A, pipeline will fail to update the model card, since `Qwen2ForCausalLM` doesn't have attribute `.create_or_update_model_card()`. **But this will not affect the model saving.** 
Bug logi:
1. Finetune with `PeftTrainer` and save leads to a modelcard with `library_name = 'peft'`.
2. When do anyother finetune with same `output_dir`, since …
=> [Model Support] Qwen2 update

scripts/run_reward_modeling.sh, scripts/run_reward_modeling_with_lisa.sh, scripts/run_reward_modeling_with_lora.sh, src/lmflow/args.py, src/lmflow/models/hf_decoder_model.py, src/lmflow/models/hf_model_mixin.py, src/lmflow/models/hf_text_regression_model.py, src/lmflow/pipeline/rm_tuner.py, src/lmflow/tokenization/hf_decoder_model.py, src/lmflow/tokenization/hf_text_regression_model.py
1. RM shell shebang fix
2. Add padding side option, by default `right` (as what LMFlow did previously), when set to `auto`, will follow the tokenizer default `padding_side`
3. Specify `num_labels=1` for `HFTextRegressionModel` to avoid some rare bugs
4. `HFTextRegressionModel` supports `text_only` and `text2text` data (only for inference, since training a reward model needs preference(paired) data)
=> Usability update

README.md, examples/vllm_inference.py, scripts/run_vllm_inference.sh, src/lmflow/args.py, src/lmflow/models/hf_model_mixin.py, src/lmflow/pipeline/auto_pipeline.py, src/lmflow/pipeline/utils/memory_safe_vllm_inference.py, src/lmflow/pipeline/vllm_inferencer.py, src/lmflow/utils/constants.py, tests/pipeline/test_memory_safe_vllm_inferencer.py
1. Add vllm inference example
2. Change `detokenize` to `decode_inference_result` to make it clearer
1. MemorySafeVLLMInference test
2. Example sh test
Note that the fetal python error comes from the killing signal. This will not affect the inference, as the results are already saved:
=> [Feature] Add vllm inference example

configs/accelerate_dsz3_config.yaml, examples/dpov2_train.py, examples/rm_inference.py, examples/vllm_inference.py, requirements.txt, scripts/run_dpo_align.sh, scripts/run_dpov2_align.sh, scripts/run_rm_inference.sh, src/lmflow/args.py, src/lmflow/datasets/dataset.py, src/lmflow/models/hf_decoder_model.py, src/lmflow/models/hf_model_mixin.py, src/lmflow/models/hf_text_regression_model.py, src/lmflow/pipeline/auto_pipeline.py, src/lmflow/pipeline/dpov2_aligner.py, src/lmflow/pipeline/rm_inferencer.py, src/lmflow/pipeline/rm_tuner.py, src/lmflow/pipeline/utils/dpov2_dataprocessor.py, src/lmflow/pipeline/utils/dpov2_trainer.py, src/lmflow/pipeline/vllm_inferencer.py, src/lmflow/tokenization/hf_text_regression_model.py, src/lmflow/utils/constants.py
1. Add reward model inferencer
2. Add DPOv2 aligner
3. rm and dpo dataset format change
See the latest comment
See the latest comment
=> [Feature] reward model inferencer and dpov2 aligner

contrib/text2image/README.md, contrib/text2image/accelerate_t2i_config.yaml, contrib/text2image/diffuser_args.py, contrib/text2image/diffuser_finetuner.py, contrib/text2image/finetune_t2i.py, contrib/text2image/finetune_t2i.sh, contrib/text2image/requirements.txt, contrib/text2image/t2i_dataset.py
Text to image fine-tuning support for Stable Diffusion 1 and 2 series.
=> [ADD] T2I finetuning with SD1 and SD2 to contrib

contrib/tool-finetune/README.md, contrib/tool-finetune/function_call_finetune.py, contrib/tool-finetune/run_function_call_finetune.sh, src/lmflow/utils/conversation_template/__init__.py, src/lmflow/utils/conversation_template/base.py, src/lmflow/utils/conversation_template/llama.py, src/lmflow/utils/conversation_template/qwen.py
=> function-call-finetune

requirements.txt
Remove the NumPy version requirement, as it may cause a conflict when installing Gradio.
=> [usability] remove numpy version requirement

README.md
For users who are having trouble installing ray, we recommend to use v0.0.8.
We will make ray, vllm and some other packages optional later #905
=> [usability] temporarily change default version to 0.0.8

README.md
=> [doc] Add wandb setup guide

requirements.txt
Temporarily restrict transformers version to solve #913 
We are working on upgrading LMFlow to fully support accelerate in the next PR, and this restriction will be removed by that time.
=> [temp] temporarily restrict transformers version

README.md
=> announce support of hymba

src/lmflow/args.py, src/lmflow/utils/constants.py
1. Fix `lora_target_modules` parsing issue
2. Add (recommended) hymba lora target
=> [usability] Add hymba lora target

README.md
Added small note under training section, added placeholder for to-be FAQ section.
=> [doc] add FAQ placeholder, add note on arguments for training

src/lmflow/args.py, src/lmflow/datasets/dataset.py, src/lmflow/models/hf_decoder_model.py, src/lmflow/pipeline/finetuner.py, src/lmflow/tokenization/hf_decoder_model.py, src/lmflow/tokenization/hf_text_regression_model.py, src/lmflow/utils/data_utils.py, src/lmflow/utils/debug/profiler.py
1. Change how lmflow verify the dataset format.
2. Users can now specify dataset cache dir by `--dataset_cache_dir xxx`, which is useful when tokenizing a big dataset and the default dir has limited space.
3. Add a simple profiler for dev uses.
> ![image](https://github.com/user-attachments/assets/6712015b-4559-4aa6-8749-93429ec60fb9)
> ![image](https://github.com/user-attachments/assets/adecfc62-9315-4c2f-afd6-733fd5224393)
> 81 json files, each contains ~2,600,000 instances. After tokenization, the cache file takes ~1.3T disk space.
> Tested on normal conversation dataset, works fine.
> Compare w/ main branch. Note: temporarily add random control (torch and np seed) thus git reports `finetuner.py` as modified.
=> [usability] Change dataset check method

src/lmflow/utils/data_utils.py
Updated the method for checking dataset types. Previously, we read the first/last 100 lines of data JSON files for validation, which caused issues when processing JSON files without proper line breaks. Now we determine the type by reading the first/last 100 characters of the file instead.
=> [fix] fix get dataset type function

train.sh
Just to make more clear that dataset path must be entered by user. Also added a comment that project dir will show users things like loss over the finetuning process.
=> [05/14/2025 02:00 PM EDT] Update train.sh 
