OptimalScale/LMFlow

src/lmflow/datasets/dataset.py
src/lmflow/pipeline/inferencer.py
tests/models/test_hf_decoder_model.py

So that the format is more intuitive, and totally the same as the input json file.
- Modify corresponding usage of thoese two interfaces accordingly

Change format of dataset.to_dict() and dataset.from_dict()

---

examples/chatbot.py
scripts/run_chatbot.sh

- Suppress warnings.warn
- Add support for lora model loading
- Change temperature to 0.7 (preferred in many default settings)

Improve chatbot interface

---

output_models/download.sh

Shizhe download link

---

requirements.txt

Update requirement for service

---

src/lmflow/models/hf_decoder_model.py

Add load with disk swapping to reduce RAM usage during loading

Add load with disk to reduce RAM usage

---

README.md

Make it in the correct location

Update README Colab badge

---

README.md
README_es.md
README_jp.md
README_ko.md
README_zh-hans.md

2003pro patch multilingual

---

src/lmflow/models/hf_decoder_model.py
tests/models/test_hf_decoder_model.py

- Add corresponding unittest as well

Add batch encode and decode for `hf_decoder_model`

---

readme/README_es.md
readme/README_hindi.md
readme/README_jp.md
readme/README_ko.md
readme/README_zh-hans.md

Fix readme dir bugs

---

examples/chatbot.py

- Also export temperature/max_new_tokens/end_string to commandline
- Fix a bug of index truncation

Add prompt in chatbot to support few-shot infer

---

data/download.sh
examples/evaluate.py
examples/raft_align.py
scripts/run_evaluation.sh
scripts/run_evaluation_with_lora.sh
scripts/run_raft_align.sh
src/lmflow/args.py
src/lmflow/datasets/dataset.py
src/lmflow/models/auto_model.py
src/lmflow/models/regression_model.py
src/lmflow/models/text_regression_model.py
src/lmflow/pipeline/auto_pipeline.py
src/lmflow/pipeline/base_aligner.py
src/lmflow/pipeline/raft_aligner.py
src/lmflow/pipeline/utils/raft_trainer.py
tests/models/test_hf_decoder_model.py

Add RAFT aligner and corresponding script. Users can directly run `./scripts/run_raft_align.sh` to align a gpt2 model.

Feature raft

---

scripts/run_evaluation.sh
scripts/run_evaluation_with_lora.sh
src/lmflow/args.py
src/lmflow/models/hf_decoder_model.py
src/lmflow/pipeline/evaluator.py
tests/models/test_hf_decoder_model.py

This reverts commit d51d293de652a04e17d811569cba39bd6d1accd7, reversing changes made to e5f1f0c502b0aa6ef00f0d7638bdbb4b97fbe44d.

Revert "Merge pull request #214 from yaoguany/main"

---

src/lmflow/pipeline/evaluator.py

- --prompt_structure is needed for this evaluation mode

Add text2text format support for eval nll

---

src/lmflow/pipeline/raft_aligner.py

The old version first gets the top alpha samples locally and sends the samples to other GPUs. The new version gathers all samples before ranking them.

improve data collection of raft

---

examples/chatbot_gradio.py

Fix gradio bug.

---

requirements.txt
setup.py
src/lmflow/models/hf_decoder_model.py

- check if device is a100 in setup
- check device in hf_decoder

Fix dependency of flash-att on A100

---

src/lmflow/models/hf_decoder_model.py

- only import flash-attn it installed in hf_decoder

Fix import issue when not using flash-attn

---

data/download.sh
examples/benchmarking.py

- update download.sh
- update LOCA_DATASET in examples/benchmark.py

Add lmflow-chat evaluation

---

README.md
scripts/run_all_benchmark.sh
scripts/run_benchmark.sh

- add scripts/run_all_benchmark.sh to achieve benchmark with model hf name/local path
- modify scripts/run_benchmark.sh to adapt scripts/run_all_benchmark.sh
- add new section on README.md

Add run_benchmark_all.sh for benchmarking

---

tests/pipeline/test_auto_pipeline.py

Testing
```
python3 -m unittest tests/pipeline/test_auto_pipeline.py
```
Results
```
----------------------------------------------------------------------
Ran 5 tests in 1.599s
OK
```

Add unit tests for auto_pipeline

---

docs/source/examples/DATASETS.md

The current command given in the Dataset docs fails. This updates the docs to give an accurate command which downloads all the datasets and some more info.

Update command in docs for downloading datasets

---

scripts/run_app.sh
service/app.py
service/templates/index.html

- support streaming response 
- support model parallelism for large model inference
- add a rest button for clearing conversation history
- accelerate inference speed by using past_key_values
- provide a shell script to run app.py

Web Demo Refactor

---

examples/reward_modeling.py

This line invalidate the setup for Lora in line 46

Fix a bug in reward_modeling.py

---

docs/source/examples/raft.md
examples/raft_align.py
scripts/run_raft_align.sh
scripts/run_reward_modeling.sh
src/lmflow/args.py
src/lmflow/pipeline/raft_aligner.py

The original imdb movie review completion task is rather limited and we will use the hh-rlhf dataset as our example.

Update raft code and use hh_rlhf as example.

---

README.md
readme/README_es.md
readme/README_hindi.md
readme/README_jp.md
readme/README_ko.md
src/lmflow/pipeline/finetuner.py

1.
change 
```
f" n_gpu: {finetuner_args.n_gpu}"
```
to
```
f" n_gpu: {finetuner_args.n_gpu},"
```
2. update readme files, based on
[a87332e55c25f357f5800b57cb4ddad521924a45](https://github.com/OptimalScale/LMFlow/pull/466/commits/a87332e55c25f357f5800b57cb4ddad521924a45)

add the missing comma and update readme

---

scripts/data_preprocess/concat.py
scripts/data_preprocess/merge.py
scripts/data_preprocess/run_data_preprocess.sh

- support merge multiple files or all json from a directory for data preprocessing
- add a script for using sample, shuffle and merge dataset

support merge multiple files for data preprocess and add a script

---

readme/README_ko.md

As a Korean, I have naturally corrected the Korean translation version of Chat GPT.

Update korean readme

---

src/lmflow/models/hf_decoder_model.py

Fix a bug that cannot tune Robin

Prevent Robin from using RAM optimized loading

---

scripts/data_preprocess/run_data_preprocess.sh

Remove a space from the data process script.

fix data process script

---

configs/ds_config_multimodal.json
examples/inference.py
examples/vis_chatbot_gradio.py
scripts/inference_multimodal_model.sh
scripts/run_inference_multimodal_model.sh
src/lmflow/args.py
src/lmflow/datasets/dataset.py
src/lmflow/models/auto_model.py
src/lmflow/models/hf_encoder_decoder_model.py
src/lmflow/pipeline/inferencer.py
src/lmflow/utils/constants.py

Support image encoder with image caption as example.
Try model: BLIP with Salesforce/blip-image-captioning-bas
Discussion:
+ the name of arch_type: visionEncoder_decoder
+ format the data with image_text
+ Should we generate another class inherited from HFEncoderDecoder?

[FEATURES] Support image encoder with image caption as example

---

src/lmflow/pipeline/utils/raft_trainer.py

need more confirmation to upgrade the transformers/deepspeed/accelerate

Fix raft latest transformers

---

experimental/RAFT-diffusion/SD256-RAFT.ipynb
experimental/RAFT-diffusion/train_text_to_image_lora.py

The SD256-RAFT notebook needs these two commits to correctly run on my google colab account.

Sd256 raft nb fixes

---

scripts/speculative_decoding/README.md

add readme for speculative decoding under ./scripts/speculative_decoding/README.md

add readme for speculative decoding

---

requirements.txt
src/lmflow/pipeline/auto_pipeline.py

- Raft is not compatible with `transformers >= 4.35.0`, add version check in `src/lmflow/pipeline/auto_pipeline.py` to avoid conflicts

Upgrade `transformers` deps to support mistral

---

src/lmflow/args.py
src/lmflow/pipeline/finetuner.py

Add LISA training strategy by callback function in the finetuner.py

add lisa code and lisa args

---

src/lmflow/args.py

 src/lmflow/args.py typo fix

---

README.md

- Change `README.md` accordingly

Add stable version 0.0.7

---

.github/workflows/documentation.yaml

See:
https://stackoverflow.com/questions/69919970/no-module-named-distutils-but-distutils-installed

Update documentation.yaml to fix github check failure when submitting PRs

---

README.md

- suggestions from https://github.com/OptimalScale/LMFlow/issues/732

Improve installation documentation in README.md

---

README.md
requirements.txt

- Fix according to https://github.com/OptimalScale/LMFlow/issues/732

Improve `README` and `requirement.txt`

---

docs/source/conf.py
docs/source/examples/DATASETS.md

typo fix and disable html_logo on documentation page

typo fix and disable html logo

---

readme/README_zh-hans.md

readme (zh) typo fix

---

requirements.txt

- As reported in https://github.com/OptimalScale/LMFlow/issues/745, its installation sometimes leads to errors

Remove flash-attn in `requirements.txt`

---

readme/README_ko.md
readme/README_zh-hans.md

ko and zh readme update

---

readme/README_ko.md

ko readme update

---

readme/README_jp.md

readme jp update

---

README.md
data/download.sh

- modify `data/download.sh` accordingly
- remove notifications in `README.md`
- improve `README.md` regarding platform issues

Recover data server

---

readme/README_jp.md
readme/README_ko.md
readme/README_zh-hans.md

remove data server address notice (ko jp zh readme)

remove data server address notice

---

readme/README_es.md
readme/README_jp.md
readme/README_zh-hans.md

readme update

---

docs/source/examples/DATASETS.md
docs/source/examples/customize_conversation_template.md
docs/source/examples/supported_conversation_template.md

custom template document update

custom template document update

---

data/download.sh
scripts/run_finetune_with_lisa.sh
src/lmflow/args.py
src/lmflow/models/hf_decoder_model.py

run llama 3 with lisa

---

contrib/README.md

Contrib README typo fix

---

README.md
scripts/run_finetune.sh
scripts/run_finetune_with_lisa.sh

- Use conversation styles instead, this improve training quality

Update examples for Full-param SFT and LISA

---

scripts/run_finetune_with_lisa.sh
scripts/run_finetune_with_lora.sh
scripts/run_finetune_with_lora_save_aggregated_weights.sh
scripts/run_finetune_with_qlora_save_aggregated_weights.sh
src/lmflow/models/hf_decoder_model.py

1. updates shell for lora and qlora, adding conversation template
2. add template to dataset fingerprint in order to avoid using cache when template changes
3. fix an argument bug when init lora

Fixes & updates on lora, qlora scripts and hf_decoder_model

---

scripts/run_finetune.sh
scripts/run_finetune_with_lisa.sh
scripts/run_finetune_with_lora.sh
scripts/run_finetune_with_lora_save_aggregated_weights.sh
scripts/run_finetune_with_qlora_save_aggregated_weights.sh

Add trust_remote_code option to finetune shells

Add trust_remote_code option to finetune shells

---

scripts/run_finetune.sh
scripts/run_finetune_with_lisa.sh
scripts/run_finetune_with_lora.sh
scripts/run_finetune_with_lora_save_aggregated_weights.sh
scripts/run_finetune_with_qlora_save_aggregated_weights.sh

Finetune shell typo fix

---

README.md

README update, adding conversation template examples

README update, adding conversation template examples

---

readme/README_zh-hans.md

README zh update

---

readme/README_es.md

README es update

---

readme/README_hindi.md

README hindi update

---

docs/source/examples/DATASETS.md

Doc dataset page update

---

README.md

Add supported models table

---

src/lmflow/models/hf_decoder_model.py
src/lmflow/tokenization/__init__.py
src/lmflow/tokenization/hf_decoder_model.py
tests/models/test_hf_decoder_model.py

1. Tokenization multiprocessing bug fix
2. Disable passing a `ConversationTemplate` object directly through `model.tokenize()` method. For customizing conversation templates, please refer to [doc](https://optimalscale.github.io/LMFlow/examples/customize_conversation_template.html).

[Bug fix] Tokenization multiprocessing fix

---

src/lmflow/models/hf_decoder_model.py
src/lmflow/tokenization/hf_decoder_model.py

1. Fix blocking function args missing issue. `conversation_tokenize_function()` now should work as desired.
2. Fix dataset fingerprint bug, now caching should work as desired.

[Bug fix] Blocking function args missing fix

---

scripts/run_reward_modeling.sh
src/lmflow/models/hf_text_regression_model.py
src/lmflow/tokenization/hf_text_regression_model.py

Fix tokenizer multiprocessing in reward model (original issue: https://github.com/OptimalScale/LMFlow/issues/482)
num_proc=4
num_proc=8

[Bug fix] Fix tokenizer multiprocessing in reward model

---

src/lmflow/models/hf_decoder_model.py
src/lmflow/models/hf_text_regression_model.py
src/lmflow/utils/constants.py

Add preset lora target modules list

[Usability] Add preset lora target modules

---

install.sh
src/lmflow/args.py
src/lmflow/models/hf_decoder_model.py
src/lmflow/models/hf_model_mixin.py
src/lmflow/models/hf_text_regression_model.py

Move some methods in `hf_decoder_model` and `hf_text_regression` to `hf_model_mixin`
1. Full-Finetune
2. LISA
3. LoRA
4. QLoRA

[Model] hf model modification and inheritance change

---

README.md
scripts/run_finetune_with_custom_optim.sh
src/lmflow/args.py
src/lmflow/optim/adabelief.py
src/lmflow/optim/adabound.py
src/lmflow/optim/adamax.py
src/lmflow/optim/adamp.py
src/lmflow/optim/adan.py
src/lmflow/optim/lamb.py
src/lmflow/optim/lars.py
src/lmflow/optim/nadam.py
src/lmflow/optim/optimizers.py
src/lmflow/optim/radam.py
src/lmflow/optim/sgdp.py
src/lmflow/optim/sophia.py
src/lmflow/optim/yogi.py
src/lmflow/pipeline/finetuner.py

Custom optimizer training is now supported with a range of optimizers. Explore the details and utilize the new features through our updated script available at scripts/run_finetune_with_custom_optim.sh.

Expanding Optimization Options

---

README.md

Glad that LMFlow received the Best Demo Paper Award at NAACL 2024! Grateful!

update naacl best paper award

---

src/lmflow/args.py
src/lmflow/pipeline/dpo_aligner.py

1. dpo eval dataset is now optional

[usability] make dpo eval dataset optional

---

src/lmflow/models/hf_model_mixin.py
src/lmflow/utils/conversation_template/base.py

Fix load from LoRA weight & empty tools and system

---

.gitignore
examples/merge_lora.py

[fix] merge lora fix

---

README.md

Change the recommended version to v0.0.9

[doc] update default branch

---

src/lmflow/args.py
src/lmflow/utils/constants.py

* [usability] add hymba lora target
* [usability] add hymba lora target
* typo fix
---------

[usability] Add hymba lora target (#924)

---

scripts/run_finetune_with_custom_optim.sh
src/lmflow/args.py
src/lmflow/optim/muon.py
src/lmflow/optim/optimizers.py
src/lmflow/pipeline/finetuner.py

I just integrated the Muon optimizer in LMFlow, which was recently recommended by the KiMi team and performed well.

Added Muon Optimizer

---

README.md
train.sh

Add Q/A for number of tokens that participants can use, as this was not directly mentioned in the original README.

Explicitly mention # of training tokens

---

train.sh

As per discussion, we should have the learning rate as 1e-5.

fix lr to 1e-5
